version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'iqvia'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3307:3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
